# This file is part of the Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# it is governed by an MIT License (MIT)
# Copyright (c) 2023 Fernando Martínez Santa 

device =  "x64"
board =   "PC"

backend = "pc"

cc_linux =      "gcc"
cc_windows =    "c:\\v\\thirdparty\\tcc\\tcc.exe"
# cc_flags = ["-0" ]

i8 =    "signed char"
i16 =   "short"
int =   "long"
i64 =   "long long"
isize = "long long"
"int literal" =   "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 =   "float"
f64 =   "double"
"float literal" =   "float"

mutex = "NOT SUPPORTED"
main_ret_type = "int"
main_params =   "none"   

api_modules =   []
  
headers =   []

macros =    []

config_operator =   []

configuration = []

initialization =    []