# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: setup.toml (PC)
# Author: Fernando Martínez Santa
# Date: 2023
# License: MIT
#
# Description: This is the setup file for the PC version of Aixt project 

device =  "x64"
board =   "PC"
backend = "pc"

cc_linux =      "gcc"
cc_windows =    "c:\\v\\thirdparty\\tcc\\tcc.exe"
cc_flags =      "-o" 

fixed_size_arrays =  "true"
# fixed_size_strings = true

void =  ""
bool =  "bool"

i8 =    "signed char"
i16 =   "short"
int =   "long"
i64 =   "long long"
isize = "long long"
int_literal = "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 =   "float"
f64 =   "double"
float_literal =   "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="
main_ret_type = "int"
main_params =   ""   

api_modules =   []
  
headers =   [ 
    "stdbool.h"
]

macros =    []

config_operator =   []

configuration = []

initialization =    []