# Project Name = Aixt project, https =//gitlab.com/fermarsan/aixt-project.git
# File Name = Explorer16-PIC24.toml
# Author = Fernando Martínez Santa
# Date = 2022-2023
# License = MIT
#
# Description = This is the setup file for the Explorer16 (with PIC24)
#               port of Aixt project 
port =    "Explorer16-PIC24"
device =  "PIC24FJ128GA010"
board =   "Explorer 16"
backend = "native"

cc_linux =   "xc16"
cc_windows = "xc16.exe"
cc_flags =   "-o"

path = "PC"

api_modules = [
    "machine",
    "time"
]

i8 =     int8_t
i16 =    int16_t
i32 =    int32_t
isize =  int16_t
int =    int32_t

u8 =     uint8_t
u16 =    uint16_t
u32 =    uint32_t
usize =  uint16_t
byte =   uint8_t

f32 =    float
f64 =    "long double"

default_int =    int16_t
default_float =  float

main_ret_type =  int
main_params =    void    

api_modules =
  - machine
  - time

headers =
  - <xc.h>
  - <stdint.h>
  - <stdbool.h>
  - <p24FJ128GA010.h>
  - <libpic30.h>

macros =
  - "FCY 4000000UL"

config_operator =  "#pragma config"

configuration =
  - "POSCMOD = XT"
  - "OSCIOFNC = ON"
  - "FCKSM = CSDCMD"
  - "FNOSC = PRI"
  - "IESO = ON"
  - "WDTPS = PS32768"
  - "FWPSA = PR128"
  - "WINDIS = ON"
  - "FWDTEN = OFF"
  - "ICS = PGx2"
  - "GWRP = OFF"
  - "GCP = OFF"
  - "JTAGEN = OFF"

initialization =
#  - ""
  - "//AD1PCFG = 0xFFFF; // set all I/O digital"

nxc =  false