# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: NXT.toml
# Author: Fernando Martínez Santa & Sergio Romero
# Date: 2022-2023
# License: MIT
#
# Description: Setup file for the Mindstorms NXT (NXC) port
port =      "NXT" 
device =    "Atmel AT91SAM7S256 + Atmel AVR ATmega48"
board =     "LEGO Mindstorms NXT intelligent brick"
backend =   "nxc"

cc_linux =   "./nbc-linux"
cc_windows = ".\\nbc-windows.exe"
cc_flags =   "-T=NXT -S=usb -d"

path = "NXT"

api_modules = []

fixed_size_arrays =  "true"
fixed_size_strings = "true"

void =  ""
bool =  "bool"

i8 =    "char"
i16 =   "int"
int =   "long"
i64 =   "NOT SUPPORTED"
isize = "long"
int_literal = "long"

u8 =    "byte"
u16 =   "unsigned int"
u32 =   "unsigned long"
u64 =   "=== NOT SUPPORTED ==="
usize = "unsigned long"

f32 =   "float"
f64 =   "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "string"

default_int =   "int"
default_float = "float"

mutex = "mutex"

main_ret_type = ""
main_params =   ""    

headers = []

macros = []

config_operator = ""

configuration = []

initialization = []


[api_functions]


[equivalents] 
out_abc =               "OUT_ABC"
out_ab =                "OUT_AB"
out_ac =                "OUT_AC"
out_bc =                "OUT_BC"
out_a =                 "OUT_A"
out_b =                 "OUT_B"
out_c =                 "OUT_C"
motor_abc =             "OUT_ABC"
motor_ab =              "OUT_AB"
motor_ac =              "OUT_AC"
motor_bc =              "OUT_BC"
motor_a =               "OUT_A"
motor_b =               "OUT_B"
motor_c =               "OUT_C"

in_1 =                  "IN_1"
in_2 =                  "IN_2"
in_3 =                  "IN_3"
in_4 =                  "IN_4"
s1 =                    "S1"
s2 =                    "S2"
s3 =                    "S3"
s4 =                    "S4"

reverse =               "OnRev"
on_reverse =            "OnRev"
on_rev =                "OnRev"
forward =               "OnFwd"
on_forward =            "OnFwd"
on_fwd =                "OnFwd"
forward_reg =           "OnFwdReg"
on_forward_reg =        "OnFwdReg"
on_fwd_reg =            "OnFwdReg"
forward_sync =          "OnFwdSync"
on_forward_sync =       "OnFwdSync"
on_fwd_sync =           "OnFwdSync"
reverse_sync =          "OnRevSync"
on_reverse_sync =       "OnRevSync"
on_rev_sync =           "OnRevSync"
off =                   "Off"
coast =                 "Coast"
    
sleep =                 "Wait"
wait =                  "Wait"

move_time =             "move_time"
turn_time =             "turn_time"
total_time =            "total_time"

random =                "Random"

set_sensor_touch =      "SetSensorTouch"
set_sensor_light =      "SetSensorLight"
set_sensor_sound =      "SetSensorSound"
set_sensor_lowspeed =   "SetSensorLowspeed"
set_sensor_type =       "SetSensorType"
set_sensor_mode =       "SetSensorMode"
set_sensor =            "SetSensor"
reset_sensor =          "ResetSensor"
clear_sensor =          "ClearSensor"

clear_screen =          "ClearScreen"

reset_motor =           "ResetMotor"
reset_screen =          "ResetScreen"
sensor_us =             "SensorUS"
delete_file =           "DeleteFile"
close_file =            "CloseFile"
create_file =           "CreateFile"

sensor_1 =              "SENSOR_1"
sensor_2 =              "SENSOR_2"
sensor_3 =              "SENSOR_3"
sensor_4 =              "SENSOR_4"

sensor_touch =          "SENSOR_TOUCH"
sensor =                "Sensor"
rotate_motor =          "RotateMotor"
rotate_motor_ex =       "RotateMotorEx"
rotate_motor_pid =      "RotateMotorPID"
acquire =               "Acquire"
release =               "Release"
precedes =              "Precedes"
play_file_ex =          "PlayFileEx"
play_tone_ex =          "PlayToneEx"
play_tone =             "PlayTone"
bluetooth_status =      "BluetoothStatus"

stop =                  "stop"
num_to_str =            "NumToStr"
str_cat =               "StrCat"
str_len =               "StrLen"
text_out =              "TextOut"
print_text =            "TextOut"
num_out =               "NumOut"
pint_num =              "NumOut"
point_out =             "PointOut"
rect_out =              "RectOut"
line_out =              "LineOut"
circle_out =            "CircleOut"
graphic_out =           "GraphicOut"

receive_remote_string = "ReceiveRemoteString"
receive_remote_number = "ReceiveRemoteNumber"
send_remote_string =    "SendRemoteString"
send_remote_number =    "SendRemoteNumber"

writeln_string =        "WriteLnString"
write_bytes =           "WriteBytes"
writeln =               "WriteLn"
current_tick =          "CurrentTick"
open_file_read =        "OpenFileRead"
readln_string =         "ReadLnString"
readln =                "ReadLn"
array_init =            "ArrayInit"
