# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: PIC16F84A.toml
# Author: Luis Alfredo Pinto Medina and Fernado Martinez Santa
# Date: 2024
# License: MIT
#
# Description: Setup file for the PIC16F84A port. It works on Linux and Windows 
#              PCs and on Android with Termux
#              
port =    "PIC16F84A" 
device =  "PIC16F84A"
board =   "Nothing"
backend = "c"

cc_linux =   "gcc"
cc_windows = "C:\Program Files\Microchip\xc8\v2.40\bin\xc8.exe"
cc_flags =   "-o"

path = "Microchip/PIC16F84A"

fixed_size_arrays  = "true"
array_default_len  = 10

fixed_size_strings = "true"
string_default_len = 20

void =  ""
bool =  "bool"

i8 =    "signed char"
i16 =   "signed short"
int =   "long"
i64 =   "=== NOT SUPPORTED ==="
isize = "=== NOT SUPPORTED ==="
int_literal = "=== NOT SUPPORTED ==="

u8 =    "unsigned char"
u16 =   "unsigned short"
u16 =   "unsigned int"
u32 =   "unsigned long"
u32 =   "unsigned long long"
u64 =   "=== NOT SUPPORTED ==="
usize = "=== NOT SUPPORTED ==="

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "=== NOT SUPPORTED ==="

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = ""
main_params =   ""   

initialization = []

[api_functions]
pin_setup   =   "machine/pin"
pin_high    =   "machine/pin"
pin_low     =   "machine/pin"
pin_write   =   "machine/pin"
pin_read    =   "machine/pin"

sleep_s     =   "time/sleep_s"
sleep_ms    =   "time/sleep_ms"
sleep_us    =   "time/sleep_us"

[aliases]