# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: PIC16F873A.toml
# Author: Cesar Alejandro Roa Acosta and Fernado Martinez Santa
# Date: 2024
# License: MIT
#
# Description: Setup file for the PIC16F873A port. It works on Linux and Windows 
#              PCs and on Android with Termux
#              
port =    "PIC16F873A" 
device =  "PIC16F873A"
board =   "Nothing"
backend = "c"

cc_linux =   "gcc"
cc_windows = "c:\Program Files\Microchip\xc8\v2.41\bin\xc8.exe"
cc_flags =   "-o"

path = "Microchip/PIC16F873A"

fixed_size_arrays  = "true"
array_default_len  = 10

fixed_size_strings = "true"
string_default_len = 20

void =  ""
bool =  "bool"

i8 =    "signed char"
i16 =   "signed short"
int =   "long"
i64 =   "=== NOT SUPPORTED ==="
isize = "=== NOT SUPPORTED ==="
int_literal = "=== NOT SUPPORTED ==="

u8 =    "unsigned char"
u16 =   "unsigned short"
u16 =   "unsigned int"
u32 =   "unsigned long"
u32 =   "unsigned long long"
u64 =   "=== NOT SUPPORTED ==="
usize = "=== NOT SUPPORTED ==="

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "=== NOT SUPPORTED ==="

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = ""
main_params =   ""   

headers = [ 
    "xc.h"
    "stdio.h"
]

macros = [
    "XTAL_FREQ 8000000"
]

config_operator = "#pragma config"

configuration = [
    "FOSC = HS",     
    "WDTE = OFF",      
    "PWRTE = OFF",      
    "BOREN = OFF",      
    "LVP = OFF",      
    "CPD = OFF",      
    "WRT = OFF",     
    "CP = OFF"      
]

initialization = []

[api_functions]
pin_setup   =   "machine/pin"
pin_high    =   "machine/pin"
pin_low     =   "machine/pin"
pin_write   =   "machine/pin"
pin_read    =   "machine/pin"

pwm_setup   =   "machine/pwm"
pwm_write   =   "machine/pwm"

adc_setup    =   "machine/adc"
adc_read     =   "machine/adc"
adc_reading  =   "machine/adc"

uart_setup  =   "machine/uart"
print       =   "machine/uart"
uart_input  =   "machine/uart"
uart_read  =    "machine/uart"

sleep       =   "time/sleep"
sleep_ms    =   "time/sleep_ms"
sleep_us    =   "time/sleep_us"

[aliases]