# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: Samd21.toml (PC)
# Authores: Carlos Zapata , Anderson Marin
# Date: 2024
# License: MIT
#
# Description: This is the setup file for the PC version of Aixt project 

port = "SAMD21G"
device = "ATSAMD21G18A-MU"
board = "XIAO SAMD21"
backend = "native"

cc_linux =      ""
cc_windows =    "PSoC_Creator.exe"                                      *// REVISAR*
cc_flags =      "-o"


path="Seeeduino_Xiao/SAMD21"

api_modules = [
    "pin",
    "time",
    "adc",
    "pwm",
    "uart"
]

fixed_size_arrays =  "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  ""
bool =  "bool"

i8 =    "byte"
i16 =   "int"
int =   "long"
i64 =   "long long x"
isize = "int32"
int_literal = "int32"

u8 =    "uint8"
u16 =   "uint16"
u32 =   "uint32"
u64 =   "uint64"
usize = "uint32"

f32 = "float32"
f64 = "float64"
float_literal = "float32"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="
main_ret_type = "int"
main_params =   "void"   

headers =   [ 
    "project.h"
]

macros =    [
   
]

config_operator =   []

configuration = []

initialization =    [
    "CyGlobalInitEnable;",
    "uart_Start();",
    "pwm0_Start();",
    "pwm1_Start();",
    "pwm2_Start();",
    "pwm3_Start();",
    "adc_Start();",
    "amux_Start();",
    
]