# This file is part of the Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# it is governed by an MIT License (MIT)
# Copyright (c) 2023 Fernando Martínez Santa 

device =    "Atmel AT91SAM7S256"
board =     "LEGO Mindstorms NXT intelligent brick"

void =  ""


backend =   "nxc"

cc_linux =       "./nbc-linux"
cc_windows =     ".\\nbc-windows.exe"

i8 =    "char"
i16 =   "int"
i32 =   "long"
i64 =   "NOT SUPPORTED"
isize = "long"
int =   "long"

u8 =    "byte"
u16 =   "unsigned int"
u32 =   "unsigned long"
u64 =   "NOT SUPPORTED"
usize = "unsigned long"

f32 =   "float"
f64 =   "NOT SUPPORTED"

rune =  "char"
bool =  "bool"

default_int =   "int"
default_float = "float"

mutex = "mutex"
main_ret_type = ""
main_params =   ""    

api_modules =   []

headers =   []

macros =    []

config_operator = ""

configuration = []

initialization =    []